

spring:
  #数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zbf2312306353
    type: com.alibaba.druid.pool.DruidDataSource
  #发送邮件配置
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 2312306353@qq.com
    password: xomzoifgdxpydjih


mybatis:
  mapper-locations: classpath:mapper/*.xml #指定mybatis映射文件路径

server:
  port: 8081
#配置日志
logging:
  file:
    name: log/log.log
  level:
    root: info
    henu: debug

